### ISSUE TITLE
Not able to add dynamic value in c#

### ISSUE THREAD

**Issue by namanjain123** [typpo/quickchart-csharp#7]
How to add dynamic value ie

 Chart qc = new Chart();

            qc.Width = 500;
            qc.Height = 300;
            qc.Config = @"{
                type: 'bar',
                data: {
                    labels: ['Q1', 'Q2', 'Q3', 'Q4'],
                    datasets: [{
                    label: 'Users',
                    data: [50, 60, 70, 180]
                    }]
                }
            }";

we need to replace label dynamically

**Comment by typpo** [comment]
Hi @namanjain123,

You can interpolate values in the config the same way you would interpolate values in any string.

For example:

```csharp
qc.Config = $"{ ... data: [{data1}, {data2}, ...]}";
```

or 

```csharp
qc.Config = "{ ... data: [" + string.Join(",", values) + "], ...}";
```

You can also use String.Format, StringBuilder, etc.
