### ISSUE TITLE
Unable to use useShortUrl

### ISSUE THREAD

**Issue by N-E-W-T-O-N** [typpo/quickchart-csharp#9]
When  I am trying to use GetShortUrl() that function is not working.

Getting error SSL connection could not be established 
@typpo 

Previous it was working fine.

**Comment by typpo** [comment]
Try making sure your local CA bundle is up-to-date.  The SSL cert for https://quickchart.io/ is valid and working.

**Comment by N-E-W-T-O-N** [comment]
@typpo  How to do that.
I am using a window pc.

**Comment by N-E-W-T-O-N** [comment]
![Screenshot 2023-10-20 121625.png](https://github.com/typpo/quickchart-csharp/assets/38786893/3ce0f50d-7f0a-4924-93d9-b5ce9216ffe1)

![Screenshot 2023-10-20 121616.png](https://github.com/typpo/quickchart-csharp/assets/38786893/9e6f9e7e-9d2a-408f-9ba6-f2d8ddab09a4)

![Screenshot 2023-10-20 121609.png](https://github.com/typpo/quickchart-csharp/assets/38786893/3ea9cbfc-3b53-408f-89f2-da19394e54ba)

I am getting the following issues

**Comment by typpo** [comment]
You'll have to do some troubleshooting here.  The problem is not on QuickChart's side.  Perhaps you can follow these instructions to use a newer version of TLS: https://stackoverflow.com/a/50746109

**Comment by N-E-W-T-O-N** [comment]
Yes indeed the issue was with my company network policy.
